const candidateId = document.body.dataset.variant || "e1";
const trialUrl = "https://read-then-speak-trial.dgd931373-a0b.workers.dev";
const candidateInfo = {
  e1: { edition: "E1 / 粉红编辑室", art: "粉红编辑插画与写作纸张" },
  e2: { edition: "E2 / 纸张花园", art: "花园纸张与编辑插画" },
  e3: { edition: "E3 / 阅读档案", art: "阅读档案与编辑插画" },
  "v4-1": { art: "粉红编辑插画与写作纸张" }
}[candidateId] || { edition: "E / 编辑室", art: "编辑插画与写作纸张" };
const stateKey = `read-then-speak-${candidateId}-v1`;
const modelKey = `read-then-speak-${candidateId}-model-v1`;
const empty = { sources: [], analysis: null, cards: [], selected: [], article: "", title: "", theme: "magazine", practiceText: "", structure: "", topicId: "", cardId: "", events: [] };
const providers = {
  deepseek: { label: "DeepSeek", hint: "推荐国内资料拆解", protocol: "openai", base: "https://api.deepseek.com", model: "deepseek-chat" },
  openai: { label: "OpenAI", hint: "OpenAI 官方接口", protocol: "openai", base: "https://api.openai.com/v1", model: "gpt-4.1-mini" },
  qwen: { label: "千问", hint: "百炼兼容接口", protocol: "openai", base: "https://dashscope.aliyuncs.com/compatible-mode/v1", model: "qwen-plus" },
  claude: { label: "Claude", hint: "Anthropic 原生接口", protocol: "anthropic", base: "https://api.anthropic.com/v1", model: "claude-sonnet-4-20250514" },
  gemini: { label: "Gemini", hint: "Google 原生接口", protocol: "gemini", base: "https://generativelanguage.googleapis.com/v1beta", model: "gemini-2.5-flash" },
  compatible: { label: "其它兼容接口", hint: "任意 OpenAI 兼容服务", protocol: "openai", base: "", model: "" }
};
let state = normalize(readState());
save();
let activeScreen = "hero";
let mapTransform = { x: 0, y: 0, scale: 1 };
let mapFullscreen = false;
let trial = { checked:false, enabled:false, siteKey:"", token:"", consent:false };

function readState() { try { return JSON.parse(localStorage.getItem(stateKey) || localStorage.getItem("read-then-speak-v2-e") || "{}"); } catch { return {}; } }
function normalize(value) { const data = Object.assign({}, empty, value && typeof value === "object" ? value : {}); for (const key of ["sources", "cards", "selected", "events"]) if (!Array.isArray(data[key])) data[key] = []; data.sources = data.sources.map((source) => ({ ...source, name:source?.name === "手动粘贴资料" ? "本轮阅读资料" : source?.name })); for (const key of ["article", "title", "practiceText", "structure", "topicId", "cardId"]) if (typeof data[key] !== "string" || data[key] === "null") data[key] = ""; if (!data.analysis || typeof data.analysis !== "object") data.analysis = null; if (!["magazine", "newspaper", "lavender"].includes(data.theme)) data.theme = "magazine"; return data; }
function save() { localStorage.setItem(stateKey, JSON.stringify(state)); }
function track(name) { state.events = [...state.events.slice(-39), { name, at: new Date().toISOString() }]; save(); }
function esc(value = "") { return String(value).replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[c]); }
function id() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }
function currentModel() { try { return JSON.parse(sessionStorage.getItem(modelKey) || "null"); } catch { return null; } }
function sourceText() { return state.sources.map((s) => `【${s.name}】\n${s.text}`).join("\n\n"); }
function show(name) { activeScreen = name; render(); if (name === "import") checkTrialStatus(); window.scrollTo({ top: 0, behavior: "smooth" }); }

function render() {
  document.body.innerHTML = `<header class="topbar"><button class="brand" data-action="home" aria-label="回到首页"><span class="brand-mark">R</span><span>读完有话说</span></button><nav class="journey" aria-label="学习路线"><button data-action="see">看透它</button><button data-action="garden">我的表达素材库</button><button data-action="practice">练一练</button></nav>${candidateInfo.edition ? `<span class="edition">${candidateInfo.edition}</span>` : ""}</header><main>
  <section class="screen hero" data-screen="hero"><div class="hero-copy">${candidateInfo.edition ? `<p class="eyebrow">${candidateInfo.edition}</p>` : ""}<h1><span class="hero-title-line">读过的书和资料，</span><span class="hero-title-line">最后要变成</span><span class="hero-title-line">你自己的表达。</span></h1><p>导入资料，整理成卡片，再开始写。</p><div class="hero-action"><span>资料只在当前浏览器读取</span><button class="primary" data-action="import">导入我的资料 <span>→</span></button></div></div><div class="hero-art" aria-label="${candidateInfo.art}"><img src="assets/e-editorial-figure-full.jpg" alt="粉红编辑插画"><div class="editorial-paper"><span>读完有话说</span><strong>将知识<br>内化成自己的话。</strong><i></i><i></i></div></div></section>
  <section class="screen" data-screen="import" hidden>${renderImport()}</section>
  <section class="screen" data-screen="model" hidden>${renderModel()}</section>
  <section class="screen" data-screen="see" hidden>${renderSee()}</section>
  <section class="screen" data-screen="garden" hidden>${renderGarden()}</section>
  <section class="screen" data-screen="practice" hidden>${renderPractice()}</section>
  <section class="screen" data-screen="write" hidden>${renderWrite()}</section>
  <section class="screen" data-screen="format" hidden>${renderFormat()}</section>
  </main><div class="toast" id="toast" hidden></div><footer>读完有话说 · Chen Hongye</footer>`;
  document.querySelectorAll("[data-screen]").forEach((el) => { el.hidden = el.dataset.screen !== activeScreen; });
  bind();
}

function renderImport() { return `<div class="heading"><p class="eyebrow">01 / 导入本轮资料</p><h2>只选你愿意用的资料。</h2><p>资料默认只在本机处理。</p></div><div class="import-grid"><div class="import-main"><button class="import-tile" data-action="files"><span class="tile-icon">⌁</span><b>上传资料</b><small>选择 Markdown 或文本文件</small></button><button class="import-tile" data-action="vault"><span class="tile-icon">◌</span><b>选择 Obsidian 笔记</b><small>主动选择文件或 Vault 文件夹</small></button><input id="files" type="file" accept=".md,.txt,text/markdown,text/plain" multiple hidden><input id="vault" type="file" accept=".md,.txt,text/markdown,text/plain" webkitdirectory multiple hidden><label class="paste-box"><b>或粘贴一段你有权使用的文字</b><textarea id="paste" maxlength="50000" placeholder="书摘、笔记、课程文字或你自己的资料……"></textarea><button class="quiet" data-action="paste">加入本轮资料</button></label></div><aside class="source-list"><div class="source-head"><span>本轮资料</span><span>${state.sources.length} 份</span></div>${renderSources()}<p class="muted">支持 .md、.txt。PDF、EPUB 与 Word 请先粘贴已确认可使用的文字。</p>${renderTrial()}</aside></div><div class="screen-action"><button class="quiet" data-action="home">返回首页</button><div><button class="quiet" data-action="model">换用自己的 AI</button><button class="primary" data-action="analyze-local" ${state.sources.length ? "" : "disabled"}>开始看透它 →</button></div></div>`; }
function renderTrial() { if (!trial.enabled) return `<p class="muted">平台免费完整拆解即将开放；目前可用的是本地提炼或你自己的 AI。</p>`; return `<section class="trial-box"><b>一次免费完整拆解</b><p>勾选确认后，本轮资料会发送给平台独立模型；网站不保存原文或你的 API Key。</p><div id="trial-turnstile"></div><label><input id="trial-consent" type="checkbox"> 我同意仅为本轮拆解发送这些资料。</label><button class="secondary" data-action="analyze-trial" ${state.sources.length && trial.consent && trial.token ? "" : "disabled"}>使用一次免费拆解 →</button></section>`; }
function renderSources() { return state.sources.length ? state.sources.map((source) => `<article class="source-row"><div><b>${esc(source.name)}</b><small>${source.text.length.toLocaleString()} 字</small></div><button data-remove="${source.id}" title="移除资料">×</button></article>`).join("") : `<p class="muted">还没有资料。导入一段文字后，就能开始看透它。</p>`; }
function renderModel() { const saved = currentModel() || { provider: "deepseek", ...providers.deepseek }; const p = providers[saved.provider] || providers.deepseek; return `<div class="heading"><p class="eyebrow">你的模型，只在这一轮使用</p><h2>选择你习惯的 AI。</h2><p>支持主流 AI 接口。</p></div><div class="provider-grid">${Object.entries(providers).map(([key, item]) => `<button class="provider ${saved.provider === key ? "selected" : ""}" data-provider="${key}">${item.label}<small>${item.hint}</small></button>`).join("")}</div><div class="model-form"><label>接口地址<input id="model-base" value="${esc(saved.base ?? p.base)}" placeholder="${esc(p.base || "粘贴 OpenAI 兼容 Base URL")}"></label><label>模型名<input id="model-name" value="${esc(saved.model ?? p.model)}" placeholder="${esc(p.model || "例如 gpt-4.1-mini")}"></label><label>API Key<input id="model-key" type="password" autocomplete="off" placeholder="只保留在当前浏览器会话"></label><p class="model-help">Key 只在本次会话保存。</p></div><div class="screen-action"><button class="quiet" data-action="import">返回资料</button><button class="primary" data-action="analyze-model" ${state.sources.length ? "" : "disabled"}>同意发送本轮资料并分析 →</button></div>`; }
function renderSee() { const a = state.analysis; const panel = state.seePanel || "map"; const routes = { map:["继续看证据", "evidence"], evidence:["继续留下闪光", "spark"], spark:["继续打开知识卡", "cards"] }; const route = panel === "cards" ? `<div class="next-step"><span>${state.selected.length ? `已选 ${state.selected.length} 张材料` : "挑一张你想留下的材料，再进入下一步"}</span><button class="primary" data-action="garden">下一步：我的表达素材库 →</button></div>` : `<div class="next-step"><span>这一部分可以稍后再回来看。</span><button class="primary" data-action="next-panel" data-next-panel="${routes[panel][1]}">下一步：${routes[panel][0]} →</button></div>`; return `<div class="heading"><p class="eyebrow">02 / 看透它</p><h2>把资料里的路，看清楚。</h2><p>先看关系，再选一条深入。</p><span class="recommended">${currentModel() ? "你的模型分析" : "本地提炼 · 未调用 AI"}</span></div><nav class="stage-nav" aria-label="看透资料"><button class="${panel === "map" ? "active" : ""}" data-panel="map">看见骨架</button><button class="${panel === "evidence" ? "active" : ""}" data-panel="evidence">捡起证据</button><button class="${panel === "spark" ? "active" : ""}" data-panel="spark">留下闪光</button><button class="${panel === "cards" ? "active" : ""}" data-panel="cards">知识卡工作台</button></nav><div class="analysis">${!a ? `<p class="muted">先导入资料。</p>` : panel === "map" ? renderMap() : panel === "evidence" ? renderEvidence() : panel === "spark" ? renderSpark() : renderWorkbench()}</div>${route}`; }
function renderMap() { const a = state.analysis; const focus = a.mapNodes.find((node) => node.id === state.mapNodeId) || a.mapNodes[0]; const tree = mapTree(a); const layout = mapLayout(tree); const view = `<div class="map-layout"><section class="map-shell map-overview"><div class="map-caption"><span>资料结构图</span><small>${tree.branches.length} 条主题线，每条逐层展开为 5 级</small></div><div class="map-toolbar"><button data-map="out" title="缩小导图" aria-label="缩小导图">−</button><button data-map="reset" title="还原导图" aria-label="还原导图">↺</button><button data-map="in" title="放大导图" aria-label="放大导图">+</button><button data-action="canvas" title="导出思维导图到 Obsidian" aria-label="导出思维导图到 Obsidian">⇩</button><button data-action="map-fullscreen" title="沉浸式查看导图" aria-label="沉浸式查看导图">⛶</button></div><svg class="mindmap" id="mindmap" viewBox="0 0 ${layout.width} ${layout.height}" role="img" aria-label="资料五层结构图，可点击主题深入查看"><g id="map-layer" transform="${mapTransformText()}">${mapSvg(tree, layout)}</g></svg></section><aside class="map-shell map-inspector"><p class="eyebrow">${focus.kind === "core" ? "核心观点" : "主题线索"}</p><h3>${esc(focus.idea)}</h3><p class="citation">${esc(focus.source)} · ${esc(focus.locator)}</p><blockquote class="quote">${esc(focus.quote)}</blockquote><p class="relationship">${focus.relation ? `它与核心观点的关系：${esc(focus.relation)}。` : "这是这份资料当前的中心判断。"}</p>${focus.topicId ? `<button class="primary" data-topic="${focus.topicId}">深入这个主题 →</button>` : ""}</aside></div>`; return mapFullscreen ? `<section class="map-fullscreen" aria-label="沉浸式思维导图"><button class="map-close" data-action="map-close" title="退出沉浸式查看" aria-label="退出沉浸式查看">×</button>${view}</section>` : view; }
function mapTree(analysis) { const root = analysis.mapNodes[0]; const branches = analysis.mapNodes.slice(1, 7).map((theme, index) => { const topic = analysis.topics.find((item) => item.id === theme.topicId); const seed = state.cards.find((card) => topic?.seedIds.includes(card.id)) || theme; const prompt = ["这里和你的经历有什么交集？", "你同意它，还是想补充一句？", "把它放回生活，会发生什么？", "你会怎样用自己的话讲？", "哪一个细节值得留下？", "它提醒你下一步做什么？"][index % 6]; return { theme, support:{ idea:theme.relation || "结构作用", subtitle:"它在全篇里的作用" }, evidence:{ idea:short(seed.quote || theme.quote, 22), subtitle:`原文证据 · ${seed.locator || theme.locator}` }, response:{ idea:prompt, subtitle:"留给你的回应" } }; }); return { root, branches }; }
function mapLayout(tree) { const row = 138; const height = Math.max(620, tree.branches.length * row + 100); return { width:1600, height, row, root:{ x:38, y:Math.round(height / 2 - 58), width:270, height:116 }, columns:[{ x:390, width:220 }, { x:665, width:200 }, { x:920, width:240 }, { x:1215, width:320 }] }; }
function mapTransformText() { return `translate(${mapTransform.x} ${mapTransform.y}) scale(${mapTransform.scale})`; }
function mapSvg(tree, layout) { const root = tree.root; const node = (item, x, y, width, depth, clickable = false) => `<g class="map-node depth-${depth} ${clickable ? "interactive" : ""} ${state.mapNodeId === item.id ? "active" : ""}" ${clickable ? `data-map-node="${item.id}"` : ""} transform="translate(${x} ${y})"><rect width="${width}" height="82" rx="4"></rect><text x="15" y="31">${esc(short(item.idea, depth === 3 ? 18 : 15))}</text><text x="15" y="59" opacity=".66">${esc(item.subtitle || item.relation || "主题线索")}</text></g>`; const rootNode = `<g class="map-node core ${state.mapNodeId === root.id ? "active" : ""}" data-map-node="${root.id}" transform="translate(${layout.root.x} ${layout.root.y})"><rect width="${layout.root.width}" height="${layout.root.height}" rx="4"></rect><text x="20" y="45">${esc(short(root.idea, 18))}</text><text x="20" y="75" opacity=".72">核心观点</text></g>`; const links = []; const nodes = tree.branches.map((branch, index) => { const y = 48 + index * layout.row; const [theme, support, evidence, response] = layout.columns; const rootX = layout.root.x + layout.root.width; const rootY = layout.root.y + layout.root.height / 2; const themeY = y + 41; links.push(`<path class="map-link root-link" d="M${rootX} ${rootY} C${rootX + 58} ${rootY}, ${theme.x - 58} ${themeY}, ${theme.x} ${themeY}"></path>`); links.push(`<path class="map-link" d="M${theme.x + theme.width} ${themeY} H${support.x}"></path>`); links.push(`<path class="map-link" d="M${support.x + support.width} ${themeY} H${evidence.x}"></path>`); links.push(`<path class="map-link" d="M${evidence.x + evidence.width} ${themeY} H${response.x}"></path>`); return node(branch.theme, theme.x, y, theme.width, 1, true) + node(branch.support, support.x, y, support.width, 2) + node(branch.evidence, evidence.x, y, evidence.width, 3) + node(branch.response, response.x, y, response.width, 4); }).join(""); return links.join("") + rootNode + nodes; }
function renderEvidence() { const items = state.analysis.evidence || []; return items.length ? `<div class="material-grid">${items.map((item) => `<article class="material"><span class="tag">${esc(item.kind)}</span><h3>${esc(item.idea)}</h3><p class="citation">${esc(item.source)} · ${esc(item.locator)}</p><blockquote class="quote">${esc(item.quote)}</blockquote><label>你的生活里有什么类似例子？<textarea data-material="${item.id}" placeholder="不必完整，只留下一点线索……">${esc(item.response || "")}</textarea></label></article>`).join("")}</div>` : `<p class="muted">本轮资料里暂时没有足够的案例、数据或故事。</p>`; }
function renderSpark() { const items = state.analysis.sparks || []; return items.length ? `<div class="material-grid">${items.map((item) => `<article class="material"><span class="tag">闪光句</span><blockquote class="quote">${esc(item.quote)}</blockquote><p class="citation">${esc(item.source)} · ${esc(item.locator)}</p><p><b>妙在：</b>${esc(item.why)}</p><p><b>连接：</b>${esc(item.connection)}</p><label>试着写一个属于你的比喻<textarea data-spark="${item.id}" placeholder="不需要像原句，只要从你的生活出发……">${esc(item.response || "")}</textarea></label></article>`).join("")}</div>` : `<p class="muted">本轮资料里还没有适合单独留下的金句或妙喻。</p>`; }
function renderWorkbench() { const a = state.analysis; const topic = a.topics.find((t) => t.id === state.topicId); const card = state.cards.find((c) => c.id === state.cardId); return `<div class="workbench"><aside class="topic-tree"><div class="topic-root">${esc(a.core.idea)}<small>${a.topics.length} 个资料主题</small></div>${a.topics.map((topic) => `<button class="topic-button ${state.topicId === topic.id ? "active" : ""}" data-topic="${topic.id}"><span class="branch">${state.topicId === topic.id ? "⌄" : "›"}</span><b>${esc(topic.name)}</b><small>${topic.generated ? `${cardsFor(topic.id).length} 张卡` : "待展开"}</small></button><p class="topic-status">${topic.generated ? "已生成，可挑一张回应" : "点开后生成这一主题的卡片"}</p>`).join("")}</aside><section class="card-detail">${!topic ? `<div class="card-placeholder">从左侧选一个你感兴趣的主题。<br>不用一下看完全部知识卡。</div>` : !topic.generated ? `<div class="card-placeholder"><div><p class="eyebrow">${esc(topic.name)}</p><p>这一支还没有展开。</p><button class="primary" data-topic="${topic.id}">生成这一主题的卡片 →</button></div></div>` : card && card.topicId === topic.id ? renderCard(card) : `<div class="card-placeholder"><div><p class="eyebrow">${esc(topic.name)}</p><p>已生成 ${cardsFor(topic.id).length} 张卡。</p>${cardsFor(topic.id).map((c) => `<button class="quiet" data-card="${c.id}">${esc(c.idea)} →</button>`).join("<br>")}</div></div>`}</section></div>`; }
function renderCard(card) { return `<div class="card-top"><div><span class="tag">${esc(card.category)}</span><h3>${esc(card.idea)}</h3></div><label class="pick"><input type="checkbox" data-pick="${card.id}" ${state.selected.includes(card.id) ? "checked" : ""}> 选入表达素材库</label></div><p class="citation">${esc(card.source)} · ${esc(card.locator)}</p><blockquote class="quote">${esc(card.quote)}</blockquote><label class="eyebrow">我想说的话</label><textarea data-response="${card.id}" maxlength="1200" placeholder="同意、反对、联想、经历，或者你自己的判断……">${esc(card.response || "")}</textarea><p class="generated-note">${card.response ? "已留下你的回应。它可以成为你文章的材料，但不会被系统改写。" : "资料不会自动进入文章。先写下你自己的话。"}</p><button class="quiet" data-action="question" data-question="${card.id}">换一个问题帮我想</button><p class="question" id="question" hidden></p></div>`; }
function renderGarden() { const selected = state.cards.filter((card) => state.selected.includes(card.id)); return `<div class="heading"><p class="eyebrow">03 / 我的表达素材库</p><h2>把以后用得上的材料，留在自己的表达素材库。</h2><p>只保存你选中的卡片和回应。</p></div><div class="garden-grid"><section class="garden"><p class="eyebrow">我的表达素材库</p><h3>本轮已选</h3>${selected.length ? `<ul class="garden-list">${selected.map((c) => `<li><span>${esc(c.category)}</span><b>${esc(c.idea)}</b><small>${c.response ? "含你的回应" : "仅资料参考"}</small></li>`).join("")}</ul>` : `<p class="muted">从知识卡工作台选中的材料，会出现在这里。</p>`}<button class="secondary" data-action="garden-write">保存到我的表达素材库</button></section><section class="garden"><p class="eyebrow">搭起自己的说法</p><h3>这些材料可以彼此照亮</h3>${renderAssembly(selected)}<p class="muted">只提示逻辑关系。</p></section></div><div class="next-step"><span>材料已经就位，可以开始组织自己的说法。</span><button class="primary" data-action="go-write">下一步：正式开始写 →</button></div>`; }
function renderAssembly(selected) { return selected.length < 2 ? `<p class="muted">选两张或更多知识卡后，这里会提示可能的关系。</p>` : selected.slice(0, 3).map((c, i) => `<div class="assembly"><b>${i === 0 ? "可以解释的观点" : i === 1 ? "可以补充的证据" : "可以留下的联想"}</b><small>${esc(c.idea)}</small></div>`).join(""); }
function renderPractice() { return `<div class="heading"><p class="eyebrow">随时练一练</p><h2>知识真正活起来，是在你说出来、写下来的时候。</h2></div><div class="practice-grid"><button class="practice-card" data-action="feynman"><span>01</span><b>费曼技巧</b><small>把复杂的东西，用大白话讲给一个完全不懂的人听。</small></button><button class="practice-card" data-action="fifteen"><span>02</span><b>十五分钟，留下一段自己的话</b><small>不追求完整，只留下今天真正想明白的一点。</small></button></div><div id="practice-work"></div><div class="next-step"><span>练习随时可以回来继续。</span><button class="primary" data-action="go-write">下一步：正式开始写 →</button></div>`; }
function renderWrite() { const structure = state.structure || recommendStructure(); const info = structureInfo(structure); const canAiWrite = userWritingMaterial().trim().length > 0; return `<div class="writing-choice"><div class="heading"><p class="eyebrow">04 / 正式写作</p><h2>选一种你更容易开始的方式。</h2></div><section class="writing-structures"><h3>先选一种写法</h3><div class="structure-grid">${["scene", "reply", "question"].map((key, index) => { const item = structureInfo(key); return `<button class="structure ${structure === key ? "recommended" : ""}" data-structure="${key}"><span class="number">0${index + 1}</span><b>${item.name}</b><small>${item.start}</small></button>`; }).join("")}</div><div class="structure-guidance"><b>${info.name}：</b>${info.steps}</div><div class="writing-route"><div><b>自己写</b><small>在下方写作台手动输入，随时保存。</small></div><button class="secondary" data-action="focus-write">自己开始写</button><div><b>AI 帮写</b><small>${canAiWrite ? "使用你留下的材料生成文章。" : "先留下回应或练习文字。"}</small></div><button class="primary" data-action="ai-write" ${canAiWrite ? "" : "disabled"}>AI 帮写 →</button></div></section><section class="write-area"><div class="write-heading"><div><p class="eyebrow">写作台</p><h2>把你的话写下来。</h2></div><button class="quiet" data-action="see">查看资料</button></div><div class="write-layout"><aside class="reference-card">${renderReference()}</aside><section class="draft-paper"><label>文章标题</label><input id="title" maxlength="80" value="${esc(state.title)}" placeholder="先不用想标题，也可以直接写正文"><label>正文</label><textarea id="article" placeholder="${esc(info.placeholder)}">${esc(state.article)}</textarea><div class="draft-foot"><span id="count">${state.article.length} 字</span><button class="primary" data-action="format">下一步：去排版 →</button></div></section></div></section></div>`; }
function recommendStructure() { return state.cards.some((c) => c.response?.trim()) ? "reply" : state.sources.length ? "scene" : "question"; }
function structureInfo(key) { return { scene: { name: "从一个场景写起", start: "想起一个真实场景", steps: "场景 → 当时的感受或困惑 → 资料带来的新理解 → 你现在的判断。", placeholder: "先写下那个真实发生过的场景。在哪里？当时发生了什么？" }, reply: { name: "回应一句话", start: "选一张已回应的知识卡", steps: "原句或观点 → 你同意或反对什么 → 一个真实经历或例子 → 你想留下的结论。", placeholder: "先写：读到这句话时，我想到的是……" }, question: { name: "带着一个问题写", start: "写下仍未想明白的问题", steps: "问题 → 资料提供的一个角度 → 你的观察或证据 → 暂时的回答。", placeholder: "先写：我一直没有想明白的是……" } }[key]; }
function renderReference() { const card = state.cards.find((c) => state.selected.includes(c.id) && c.response?.trim()); return card ? `<p class="eyebrow">当前参考卡</p><h3>${esc(card.idea)}</h3><p class="citation">${esc(card.source)} · ${esc(card.locator)}</p><blockquote class="quote">${esc(card.quote)}</blockquote><p><b>我想说的话</b></p><p>${esc(card.response)}</p><button class="quiet" data-copy="${card.id}">放进正文</button>` : `<p class="muted">选择了直接开始。需要资料时，随时回到“看透它”。</p>`; }
const formatThemes = { magazine: { label:"编辑杂志", detail:"封面级标题、粉色荧光和引文卡", kicker:"READ THEN SPEAK / EDITION" }, newspaper: { label:"深度长文", detail:"报头、首字下沉、双栏阅读和蓝灰重点", kicker:"THE READING NOTE / LONGFORM" }, lavender: { label:"薰衣草书信", detail:"柔紫题签、手写感摘句和信纸节奏", kicker:"A QUIET LETTER / TO MYSELF" } };
function renderFormat() { const selected = formatThemes[state.theme] || formatThemes.magazine; return `<div class="heading"><p class="eyebrow">05 / 小互式排版</p><h2>同一篇文章，做成三种一眼不同的阅读体验。</h2><p>选一种，再保存。</p></div><section class="format-gallery" aria-label="三种文章排版预览">${Object.entries(formatThemes).map(([key, theme]) => `<article class="format-preview ${key} ${state.theme === key ? "selected" : ""}"><div class="format-preview-head"><span>${theme.kicker}</span><b>${theme.label}</b></div><div class="preview-paper ${key}">${preview(key)}</div><button class="format-select ${state.theme === key ? "selected" : ""}" data-theme="${key}">${state.theme === key ? "已选用此风格" : `选用${theme.label}`}</button></article>`).join("")}</section><div class="format-note"><span>专业编辑标注</span><p>自动标出核心判断与知识卡。</p></div><div class="next-step"><span>选择好风格后，就可以得到可直接保存的文章页面。</span><button class="primary" data-action="html">下一步：保存「${selected.label}」排版 ↓</button></div>`; }
function formatTerms() { const knowledgeTerms = [state.analysis?.core?.idea, ...state.cards.filter((card) => state.selected.includes(card.id)).map((card) => card.idea)]; const fallbackTerms = state.article.match(/(?:真正|自己|开始|不是|只有|重要|能够|应该)[\u4e00-\u9fff]{2,6}/g) || []; return [...new Set([...knowledgeTerms, ...fallbackTerms].filter((term) => typeof term === "string" && term.trim().length >= 3).map((term) => term.trim().slice(0, 16)))].slice(0, 5); }
function marked(value) { return formatTerms().reduce((html, term) => html.split(esc(term)).join(`<mark>${esc(term)}</mark>`), esc(value)); }
function formatParagraphs() { return state.article.split(/\n{2,}/).map((part) => part.trim()).filter(Boolean); }
function displayTitle() { const title = state.title.trim() || "未命名文章"; const compact = title.replace(/\s/g, ""); if (/^[\u4e00-\u9fff，。！？、；：,.!?;:]{9,}$/.test(compact)) { const pivot = Math.ceil(compact.length / 2); return `${esc(compact.slice(0, pivot))}<br>${esc(compact.slice(pivot))}`; } return esc(title); }
function previewContent(theme) { const parts = formatParagraphs(); if (!parts.length) return `<article class="preview-content"><p class="preview-empty">你的文章会在这里预览。回到写作台，把真正想说的话写下来。</p></article>`; return `<article class="preview-content">${parts.map((part, index) => { const paragraph = `<p class="${index === 0 ? "preview-lede" : ""}">${marked(part).replace(/\n/g, "<br>")}</p>`; if (theme === "magazine" && index === 1) return `<aside class="preview-pullquote">${marked(short(part, 42))}</aside>${paragraph}`; if (theme === "newspaper" && index === 1) return `<div class="preview-rule" aria-hidden="true"></div>${paragraph}`; if (theme === "lavender" && index === 1) return `<aside class="preview-pullquote">${marked(short(part, 34))}</aside>${paragraph}`; return paragraph; }).join("")}</article>`; }
function preview(theme) { const config = formatThemes[theme]; return `<header><span>${config.kicker}</span><h1>${displayTitle()}</h1><small>读完有话说</small></header>${previewContent(theme)}`; }

function bind() {
  document.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", () => action(button.dataset.action, button)));
  document.querySelectorAll("[data-remove]").forEach((button) => button.addEventListener("click", () => { state.sources = state.sources.filter((source) => source.id !== button.dataset.remove); save(); show("import"); }));
  document.querySelectorAll("[data-provider]").forEach((button) => button.addEventListener("click", () => selectProvider(button.dataset.provider)));
  document.querySelectorAll("[data-panel]").forEach((button) => button.addEventListener("click", () => { state.seePanel = button.dataset.panel; save(); show("see"); }));
  document.querySelectorAll("[data-topic]").forEach((button) => button.addEventListener("click", () => openTopic(button.dataset.topic)));
  document.querySelectorAll("[data-card]").forEach((button) => button.addEventListener("click", () => { state.cardId = button.dataset.card; save(); show("see"); }));
  document.querySelectorAll("[data-map-node]").forEach((node) => node.addEventListener("click", () => { state.mapNodeId = node.dataset.mapNode; save(); show("see"); }));
  document.querySelectorAll("[data-map]").forEach((button) => button.addEventListener("click", () => moveMap(button.dataset.map)));
  bindMapPan();
  document.querySelectorAll("[data-pick]").forEach((input) => input.addEventListener("change", () => { state.selected = input.checked ? [...new Set([...state.selected, input.dataset.pick])] : state.selected.filter((key) => key !== input.dataset.pick); save(); }));
  document.querySelectorAll("[data-response]").forEach((input) => input.addEventListener("input", () => updateCard(input.dataset.response, "response", input.value)));
  document.querySelectorAll("[data-material]").forEach((input) => input.addEventListener("input", () => updateItem("evidence", input.dataset.material, input.value)));
  document.querySelectorAll("[data-spark]").forEach((input) => input.addEventListener("input", () => updateItem("sparks", input.dataset.spark, input.value)));
  document.querySelectorAll("[data-structure]").forEach((button) => button.addEventListener("click", () => { state.structure = button.dataset.structure; save(); show("write"); }));
  document.querySelectorAll("[data-theme]").forEach((button) => button.addEventListener("click", () => { state.theme = button.dataset.theme; save(); show("format"); }));
  document.querySelector("#files")?.addEventListener("change", (event) => readFiles(event.target.files)); document.querySelector("#vault")?.addEventListener("change", (event) => readFiles(event.target.files, "vault_selected"));
  document.querySelector("#title")?.addEventListener("input", captureDraft); document.querySelector("#article")?.addEventListener("input", captureDraft);
  document.querySelector("#trial-consent")?.addEventListener("change", (event) => { trial.consent = event.target.checked; updateTrialButton(); });
  if (trial.enabled) initTurnstile();
}
function action(name, button) { const screens = { home:"hero", import:"import", model:"model", see:"see", garden:"garden", practice:"practice", write:"write", format:"format" }; if (screens[name]) return show(screens[name]); if (name === "files") return document.querySelector("#files").click(); if (name === "vault") return window.showDirectoryPicker ? pickDirectory() : document.querySelector("#vault").click(); if (name === "paste") return addPaste(); if (name === "analyze-local") return analyzeLocal(); if (name === "analyze-model") return analyzeWithModel(); if (name === "analyze-trial") return analyzeTrial(); if (name === "next-panel") { state.seePanel = button.dataset.nextPanel; save(); return show("see"); } if (name === "go-write") return show("write"); if (name === "focus-write") return document.querySelector("#article")?.focus(); if (name === "ai-write") return generateArticle(); if (name === "canvas") return downloadCanvas(); if (name === "map-fullscreen") { mapFullscreen = true; return render(); } if (name === "map-close") { mapFullscreen = false; return render(); } if (name === "garden-write") return writeGarden(); if (name === "garden-download") return downloadGarden(); if (name === "feynman") return renderFeynman(); if (name === "fifteen") return renderFifteen(); if (name === "format") { captureDraft(); return show("format"); } if (name === "html") return downloadHtml(); if (name === "copy") return copyResponse(button.dataset.copy); if (name === "question") return question(button.dataset.question); }
function selectProvider(provider) { const item = providers[provider]; sessionStorage.setItem(modelKey, JSON.stringify({ provider, protocol: item.protocol, base: item.base, model: item.model })); show("model"); }
async function readFiles(files, event = "sources_added") { const valid = [...files].filter((file) => /\.(md|txt)$/i.test(file.name)); if (!valid.length) return toast("请选择 Markdown 或文本文件。PDF 请先粘贴已确认的文字。"); const additions = await Promise.all(valid.map(async (file) => ({ id:id(), name:file.webkitRelativePath || file.name, text:(await file.text()).trim() }))); state.sources.push(...additions.filter((file) => file.text)); save(); track(event); show("import"); }
async function pickDirectory() { try { const root = await window.showDirectoryPicker({ mode:"read" }); await readFiles(await collectFiles(root), "vault_selected"); } catch (error) { if (error.name !== "AbortError") toast("无法读取文件夹。也可以直接选择 Markdown 文件。"); } }
async function collectFiles(folder, prefix = "") { const files = []; for await (const entry of folder.values()) { if (entry.kind === "file" && /\.(md|txt)$/i.test(entry.name)) { const file = await entry.getFile(); Object.defineProperty(file, "webkitRelativePath", { value:`${prefix}${entry.name}` }); files.push(file); } if (entry.kind === "directory" && !entry.name.startsWith(".")) files.push(...await collectFiles(entry, `${prefix}${entry.name}/`)); } return files; }
function addPaste() { const input = document.querySelector("#paste"); if (!input?.value.trim()) return toast("先粘贴一段你有权使用的资料。"); state.sources.push({ id:id(), name:"本轮阅读资料", text:input.value.trim() }); save(); track("pasted_source_added"); show("import"); }
async function checkTrialStatus() { if (trial.checked) return; trial.checked = true; const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 2500); try { const response = await fetch(`${trialUrl}/v1/trial-status`, { signal:controller.signal }); const value = response.ok ? await response.json() : {}; if (value.enabled && value.siteKey) { trial = { ...trial, enabled:true, siteKey:value.siteKey }; if (activeScreen === "import") render(); } } catch { /* The local and BYOK paths remain fully available. */ } finally { clearTimeout(timeout); } }
function initTurnstile() { const target = document.querySelector("#trial-turnstile"); if (!target || !trial.siteKey || target.dataset.ready) return; const mount = () => { if (!window.turnstile || target.dataset.ready) return; target.dataset.ready = "true"; window.turnstile.render(target, { sitekey:trial.siteKey, callback:(token) => { trial.token = token; updateTrialButton(); }, "expired-callback":() => { trial.token = ""; updateTrialButton(); } }); }; if (window.turnstile) return mount(); const script = document.createElement("script"); script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit"; script.async = true; script.defer = true; script.onload = mount; document.head.append(script); }
function updateTrialButton() { const button = document.querySelector("[data-action='analyze-trial']"); if (button) button.disabled = !(state.sources.length && trial.consent && trial.token); }
function trialId() { const key = "read-then-speak-trial-id-v1"; let value = localStorage.getItem(key); if (!value) { value = id(); localStorage.setItem(key, value); } return value; }
async function analyzeTrial() { if (!trial.consent || !trial.token) return toast("请先完成确认和人机验证。"); try { toast("正在用免费体验看透这份资料……"); const response = await fetch(`${trialUrl}/v1/trial-analysis`, { method:"POST", headers:{ "content-type":"application/json" }, body:JSON.stringify({ anonymousId:trialId(), turnstileToken:trial.token, sources:state.sources.map(({ name, text }) => ({ name, text })) }) }); const value = await response.json(); if (!response.ok) throw new Error(value.message || "免费体验暂时不可用"); applyModelAnalysis(value.analysis); track("analysis_generated_trial"); show("see"); } catch (error) { toast(`未能完成免费拆解：${error.message || "请稍后再试"}`); } }
function splitSource(source) { const clean = source.text.replace(/^---[\s\S]*?---\s*/m, "").replace(/!\[\[.*?\]\]/g, "").replace(/```[\s\S]*?```/g, "").trim(); return clean.split(/\n{2,}|(?<=[。！？])/).map((part) => part.replace(/^#{1,6}\s*/, "").trim()).filter((part) => part.length >= 28).map((quote, index) => ({ id:id(), source:source.name, locator:`第 ${index + 1} 段`, quote:quote.slice(0, 180), idea:idea(quote), category:category(quote), response:"" })); }
function category(text) { if (/[\d一二三四五六七八九十]+(年|月|天|次|个|%|％)|数据|研究|统计/.test(text)) return "证据"; if (/故事|有一次|曾经|后来|经历|朋友|自己/.test(text)) return "故事"; if (/像|仿佛|犹如|不是.*而是|温水/.test(text)) return "比喻"; return "观点"; }
function idea(text) { const value = text.replace(/[“”'‘’]/g, "").replace(/[。！？]$/, "").trim(); if (value.length <= 36) return value; const point = Math.max(value.lastIndexOf("，", 45), value.lastIndexOf("、", 45), 50); return `${value.slice(0, Math.min(point, 72))}…`; }
function short(text, length) { return text.length > length ? `${text.slice(0, length)}…` : text; }
function buildAnalysis(cards) { const core = cards[0]; const topics = groupTopics(cards); const nodes = [Object.assign({ kind:"core", relation:"", topicId:"" }, core), ...topics.slice(0, 6).map((topic, index) => { const card = cards.find((item) => topic.seedIds.includes(item.id)) || core; return Object.assign({ kind:"theme", relation:["并列", "递进", "因果", "转折", "补充", "例证"][index % 6], topicId:topic.id }, card, { idea:topic.name }); })]; return { core, structure:"围绕核心观点展开", mapNodes:nodes, topics, evidence:cards.filter((card) => ["证据", "故事"].includes(card.category)).map((card) => Object.assign({ kind:card.category }, card)), sparks:cards.filter((card) => card.category === "比喻").map((card) => Object.assign({ why:"它把抽象感受放进了一个可感知的画面。", connection:"抽象判断 ↔ 日常经验" }, card)) }; }
function groupTopics(cards) { const count = Math.max(1, Math.min(6, Math.ceil(cards.length / 2))); return Array.from({ length:count }, (_, index) => { const card = cards[index] || cards[0]; return { id:id(), name:short(card?.idea || `主题 ${index + 1}`, 16), summary:card?.quote || "", generated:false, seedIds:cards.filter((_, i) => i % count === index).map((item) => item.id) }; }); }
function analyzeLocal() { const old = new Map(state.cards.map((card) => [`${card.source}|${card.locator}|${card.quote}`, { response:card.response, selected:state.selected.includes(card.id) }])); const base = state.sources.flatMap(splitSource); state.cards = base.map((card) => Object.assign(card, old.get(`${card.source}|${card.locator}|${card.quote}`) || {})); state.selected = state.cards.filter((card) => card.selected).map((card) => card.id); state.cards.forEach((card) => delete card.selected); if (!state.cards.length) return toast("这些资料里没有足够的文字可以生成材料。"); state.analysis = buildAnalysis(state.cards); state.mapNodeId = state.analysis.mapNodes[0].id; state.seePanel = "map"; save(); track("analysis_generated_local"); show("see"); }
function cardsFor(topicId) { return state.cards.filter((card) => card.topicId === topicId); }
async function openTopic(topicId) { const topic = state.analysis?.topics.find((item) => item.id === topicId); if (!topic) return; state.topicId = topicId; if (!topic.generated) { toast("正在展开这一主题的卡片……"); const mapped = state.cards.filter((card) => topic.seedIds.includes(card.id)); mapped.forEach((card) => { card.topicId = topicId; }); topic.generated = true; if (currentModel()?.key) await enrichTopic(topic, mapped); state.cardId = cardsFor(topicId)[0]?.id || ""; track("topic_opened"); save(); } show("see"); }
async function enrichTopic(topic, cards) { try { const result = await requestModel(`只分析主题“${topic.name}”。返回 JSON：{"cards":[{"idea":"","category":"观点|证据|故事|比喻","source":"","locator":"","quote":""}]}。每项都必须来自资料，不写文章。\n\n资料：\n${sourceText()}`); if (result.article || result.title) throw new Error("模型返回了不属于拆解的文章"); const list = Array.isArray(result.cards) ? result.cards : []; const fresh = list.filter((card) => card?.idea && validSourceItem(card)).slice(0, 8).map((card) => ({ id:id(), topicId:topic.id, response:"", source:card.source, locator:card.locator, quote:card.quote, idea:card.idea, category:card.category || "观点" })); if (fresh.length) state.cards = [...state.cards.filter((card) => card.topicId !== topic.id || !topic.seedIds.includes(card.id)), ...fresh]; } catch { toast("模型没有补充可回溯的卡片，已保留本地提炼结果。"); } }
async function analyzeWithModel() { const saved = currentModel() || {}; const provider = saved.provider || "deepseek"; const base = document.querySelector("#model-base")?.value.trim().replace(/\/$/, ""); const model = document.querySelector("#model-name")?.value.trim(); const key = document.querySelector("#model-key")?.value.trim() || saved.key; if (!base || !model || !key) return toast("请填写接口地址、模型名和 API Key。"); if (sourceText().length > 50_000) return toast("本轮资料超过 5 万字，请先减少资料后再调用模型。"); sessionStorage.setItem(modelKey, JSON.stringify({ provider, protocol:providers[provider]?.protocol || "openai", base, model, key })); const sourceNames = state.sources.map((source) => source.name).join("、"); const prompt = `你是“读完有话说”的资料分析器。只分析用户资料，不写标题、文章、段落或衔接句，不把资料当成用户观点。返回严格 JSON：{"core":{"idea":"","source":"","locator":"","quote":""},"mapNodes":[{"idea":"","source":"","locator":"","quote":"","relation":"并列|递进|因果|转折|补充|例证"}],"topics":[{"name":"","summary":"","source":"","locator":"","quote":""}],"evidence":[{"idea":"","kind":"证据|故事","source":"","locator":"","quote":""}],"sparks":[{"quote":"","why":"","connection":"","source":"","locator":""}]}.\n\n导图规则：mapNodes 只能有 3 到 6 个，每个是主题级判断，不是段落摘抄；idea 控制在 16 个汉字内。每项 source 必须逐字使用下列文件名之一：${sourceNames}。quote 必须从对应资料逐字复制至少 8 个连续字符，不得改写标点或省略；locator 写清段落定位。\n\n资料：\n${sourceText()}`;
  try { toast("正在用你选择的 AI 看透这份资料……"); const result = await requestModel(prompt); applyModelAnalysis(result); track("analysis_generated_model"); show("see"); } catch (error) { toast(`未能完成分析：${error.message || "请检查模型配置"}`); }
}
async function requestModel(prompt) { const config = currentModel(); if (!config?.key) throw new Error("请先填写 API Key"); if (config.protocol === "anthropic") { const response = await fetch(`${config.base}/messages`, { method:"POST", headers:{ "content-type":"application/json", "x-api-key":config.key, "anthropic-version":"2023-06-01" }, body:JSON.stringify({ model:config.model, max_tokens:4000, messages:[{ role:"user", content:prompt }] }) }); if (!response.ok) throw new Error(`模型服务返回 ${response.status}`); const body = await response.json(); return jsonFromText(body.content?.[0]?.text || ""); }
  if (config.protocol === "gemini") { const response = await fetch(`${config.base}/models/${config.model}:generateContent?key=${encodeURIComponent(config.key)}`, { method:"POST", headers:{ "content-type":"application/json" }, body:JSON.stringify({ contents:[{ parts:[{ text:prompt }] }], generationConfig:{ responseMimeType:"application/json" } }) }); if (!response.ok) throw new Error(`模型服务返回 ${response.status}`); const body = await response.json(); return jsonFromText(body.candidates?.[0]?.content?.parts?.[0]?.text || ""); }
  const endpoint = `${config.base}/chat/completions`; const headers = { "content-type":"application/json", Authorization:`Bearer ${config.key}` }; const payload = { model:config.model, temperature:.2, messages:[{ role:"user", content:prompt }] }; let response = await fetch(endpoint, { method:"POST", headers, body:JSON.stringify({ ...payload, response_format:{ type:"json_object" } }) }); if ([400, 422].includes(response.status)) response = await fetch(endpoint, { method:"POST", headers, body:JSON.stringify(payload) }); if (!response.ok) throw new Error(`模型服务返回 ${response.status}`); const body = await response.json(); return jsonFromText(body.choices?.[0]?.message?.content || ""); }
function jsonFromText(text) { try { return JSON.parse(text.replace(/^```json\s*|```$/g, "").trim()); } catch { throw new Error("模型没有返回可用的结构化结果"); } }
function userWritingMaterial() { const responses = state.cards.filter((card) => card.response?.trim()).map((card) => `【我的回应：${card.idea}】\n${card.response.trim()}`); const practice = state.practiceText?.trim() ? [`【我的练习】\n${state.practiceText.trim()}`] : []; return [...responses, ...practice].join("\n\n"); }
function selectedSourceMaterial() { return state.cards.filter((card) => state.selected.includes(card.id)).map((card) => `【${card.source} · ${card.locator}】\n观点：${card.idea}\n原句：${card.quote}`).join("\n\n"); }
async function generateArticle() { const personal = userWritingMaterial(); if (!personal.trim()) return toast("先留下至少一条回应或一段练习文字。", ""); if (!currentModel()?.key) { toast("先设置你自己的 AI，才能帮你写文章。", ""); return show("model"); } const prompt = `你是“读完有话说”的写作协作者。根据用户已经写下的内容与被选择的资料，生成一篇可编辑的中文文章。\n\n必须遵守：\n1. 只使用下方用户内容和资料，不虚构个人经历、引用、数据或出处。\n2. 用户内容是文章的主角；资料仅用于解释、补充或支撑。\n3. 不提及你是 AI，不添加任何“初稿”或元信息。\n4. 返回严格 JSON：{"title":"","article":""}。article 用自然分段，段落之间用两个换行。\n\n用户已经写下的内容：\n${personal.slice(0, 18000)}\n\n用户选择的资料：\n${selectedSourceMaterial().slice(0, 12000) || "（没有额外选择资料）"}`; try { toast("正在根据你留下的内容组织文章……"); const result = await requestModel(prompt); if (typeof result?.article !== "string" || !result.article.trim()) throw new Error("模型没有返回文章内容"); state.title = typeof result.title === "string" ? result.title.trim().slice(0, 80) : state.title; state.article = result.article.trim(); save(); track("article_generated_byok"); show("write"); toast("文章已经放进写作台，可以继续按你的意思修改。", "success"); } catch (error) { toast(`未能完成写作：${error.message || "请检查模型配置"}`); } }
function validSourceItem(item) { const source = state.sources.find((entry) => entry.name === item?.source); return Boolean(source && String(item?.locator || "").trim() && String(item?.quote || "").trim().length >= 4 && source.text.includes(String(item.quote).trim())); }
function applyModelAnalysis(value) { if (!value || value.article || value.title) throw new Error("模型返回了不属于资料拆解的文章"); if (!validSourceItem(value.core)) throw new Error("模型返回的核心观点缺少有效出处"); const make = (item) => ({ id:id(), source:item.source, locator:item.locator, quote:item.quote, idea:item.idea || idea(item.quote), category:item.category || "观点", response:"" }); const core = make(value.core); const rawNodes = (Array.isArray(value.mapNodes) ? value.mapNodes : []).filter(validSourceItem).slice(0, 6).map((item) => Object.assign(make(item), { kind:"theme", relation:item.relation || "补充" })); if (!rawNodes.length) throw new Error("模型返回的关系图缺少可回溯节点"); const rawTopics = (Array.isArray(value.topics) ? value.topics : []).filter((item) => item?.name && validSourceItem(item)).slice(0, Math.min(6, rawNodes.length)); const topics = rawTopics.length ? rawTopics.map((topic) => ({ id:id(), name:short(topic.name, 16), summary:topic.summary || "", generated:false, seedIds:[] })) : groupTopics(rawNodes); rawNodes.forEach((node, index) => { node.idea = short(node.idea, 16); node.topicId = topics[index % topics.length].id; topics[index % topics.length].seedIds.push(node.id); }); state.cards = rawNodes.map((node) => Object.assign({}, node)); const evidence = (Array.isArray(value.evidence) ? value.evidence : []).filter(validSourceItem).map((item) => Object.assign(make(item), { kind:item.kind || "证据" })); const sparks = (Array.isArray(value.sparks) ? value.sparks : []).filter(validSourceItem).map((item) => ({ id:id(), source:item.source, locator:item.locator, quote:item.quote, why:item.why || "它把抽象感受放进了一个可感知的画面。", connection:item.connection || "抽象判断 ↔ 日常经验", response:"" })); state.analysis = { core, structure:"由资料原文支撑", mapNodes:[Object.assign(core, { kind:"core", relation:"", topicId:"" }), ...rawNodes], topics, evidence, sparks }; state.mapNodeId = core.id; state.seePanel = "map"; save(); }
function updateCard(cardId, key, value) { const card = state.cards.find((item) => item.id === cardId); if (card) card[key] = value; save(); }
function updateItem(group, itemId, value) { const item = state.analysis?.[group]?.find((entry) => entry.id === itemId); if (item) item.response = value; save(); }
function question(cardId) { const card = state.cards.find((item) => item.id === cardId); const box = document.querySelector("#question"); if (!card || !box) return; const list = card.response ? ["这句话里，哪一个细节只有你经历过？", "如果读者不同意，你最想解释哪一点？", "在哪个真实场景里最能说明它？"] : ["读到这里时，你想起了哪一个真实场景？", "你是同意、反对，还是觉得它少说了什么？", "如果讲给朋友听，你会换成什么白话？"]; box.textContent = list[Math.abs(hash(`${card.id}${card.response.length}`)) % list.length]; box.hidden = false; track("socratic_prompted"); }
function hash(value) { return [...value].reduce((total, item) => total + item.charCodeAt(0), 0); }
function captureDraft() { const title = document.querySelector("#title"); const article = document.querySelector("#article"); if (title) state.title = title.value; if (article) { state.article = article.value; const count = document.querySelector("#count"); if (count) count.textContent = `${state.article.length} 字`; } save(); }
function copyResponse(cardId) { const card = state.cards.find((item) => item.id === cardId); const editor = document.querySelector("#article"); if (!card?.response || !editor) return; editor.value += `${editor.value.trim() ? "\n\n" : ""}${card.response}`; captureDraft(); toast("已放进正文。你可以继续修改。", "success"); }
function applyMapTransform() { const layer = document.querySelector("#map-layer"); if (layer) layer.setAttribute("transform", mapTransformText()); }
function moveMap(direction) { if (direction === "reset") mapTransform = { x:0, y:0, scale:1 }; if (direction === "in") mapTransform.scale = Math.min(1.55, mapTransform.scale + .15); if (direction === "out") mapTransform.scale = Math.max(.65, mapTransform.scale - .15); applyMapTransform(); }
function bindMapPan() { const map = document.querySelector("#mindmap"); if (!map) return; let drag = null; map.addEventListener("pointerdown", (event) => { if (event.target.closest(".map-node")) return; drag = { x:event.clientX, y:event.clientY, startX:mapTransform.x, startY:mapTransform.y }; map.setPointerCapture(event.pointerId); map.classList.add("dragging"); }); map.addEventListener("pointermove", (event) => { if (!drag) return; const box = map.getBoundingClientRect(); mapTransform.x = drag.startX + (event.clientX - drag.x) * (map.viewBox.baseVal.width / box.width); mapTransform.y = drag.startY + (event.clientY - drag.y) * (map.viewBox.baseVal.height / box.height); applyMapTransform(); }); const finish = () => { drag = null; map.classList.remove("dragging"); }; map.addEventListener("pointerup", finish); map.addEventListener("pointercancel", finish); }
function canvasData() { const tree = mapTree(state.analysis); const layout = mapLayout(tree); const nodes = [{ id:"0000000000000000", type:"text", x:layout.root.x, y:layout.root.y, width:layout.root.width, height:116, color:"4", text:`# ${tree.root.idea}\n\n${tree.root.source} · ${tree.root.locator}\n\n> ${tree.root.quote}` }]; const edges = []; tree.branches.forEach((branch, index) => { const y = 48 + index * layout.row; const ids = [1, 2, 3, 4].map((depth) => (index * 4 + depth).toString(16).padStart(16, "0")); const entries = [[branch.theme.idea, `${branch.theme.source} · ${branch.theme.locator}\n\n> ${branch.theme.quote}`, "6"], [branch.support.idea, branch.support.subtitle, "3"], [branch.evidence.idea, branch.evidence.subtitle, "2"], [branch.response.idea, branch.response.subtitle, "1"]]; entries.forEach(([title, detail, color], depth) => nodes.push({ id:ids[depth], type:"text", x:layout.columns[depth].x, y, width:layout.columns[depth].width, height:82, color, text:`# ${title}\n\n${detail}` })); const chain = ["0000000000000000", ...ids]; chain.slice(1).forEach((toNode, depth) => edges.push({ id:(index * 4 + depth).toString(16).padStart(16, "f"), fromNode:chain[depth], fromSide:"right", toNode, toSide:"left", toEnd:"arrow", color:depth ? "3" : "6", label:depth === 0 ? branch.theme.relation || "主题" : "逐层展开" })); }); return { nodes, edges }; }
function downloadCanvas() { if (!state.analysis) return; download("本轮资料思维导图.canvas", JSON.stringify(canvasData(), null, 2), "application/json;charset=utf-8"); toast("已下载 Obsidian Canvas，可直接拖入 Vault。", "success"); }
function gardenNote(card) { return `---\ntags:\n  - 读完有话说\n  - ${card.category}\nsource: ${card.source}\n---\n\n# ${card.idea}\n\n## 原文出处\n${card.source} · ${card.locator}\n\n> ${card.quote}\n\n## 我想说的话\n${card.response || "（尚未写下回应；仅作资料参考。）"}\n`; }
function gardenOverview() { const tree = state.analysis?.mapNodes.slice(1).map((node) => `  - ${node.idea}（${node.relation}）`).join("\n") || "  - 本轮尚未生成关系图"; return `# 本轮拆解总览\n\n## 核心观点\n${state.analysis?.core?.idea || "未生成"}\n\n## 思维导图\n- ${state.analysis?.core?.idea || "核心观点"}\n${tree}\n\n## 已选材料\n${state.cards.filter((card) => state.selected.includes(card.id)).map((card) => `- [[${safeName(card.idea)}]]`).join("\n") || "- 尚未选择"}\n`; }
function safeName(value) { return value.replace(/[\\/:*?"<>|]/g, "").slice(0, 60) || "未命名卡片"; }
async function writeGarden() { const cards = state.cards.filter((card) => state.selected.includes(card.id)); if (!cards.length) return toast("先选择想保存到表达素材库的知识卡。"); if (!window.showDirectoryPicker) return downloadGarden(); try { const root = await window.showDirectoryPicker({ mode:"readwrite" }); const folder = await root.getDirectoryHandle("读完有话说-表达素材库", { create:true }); for (const type of ["观点", "证据", "故事", "比喻"]) await folder.getDirectoryHandle(type, { create:true }); for (const card of cards) { const bucket = await folder.getDirectoryHandle(card.category, { create:true }); const handle = await bucket.getFileHandle(`${safeName(card.idea)}.md`, { create:true }); const writer = await handle.createWritable(); await writer.write(gardenNote(card)); await writer.close(); } const overview = await folder.getFileHandle("本轮拆解总览.md", { create:true }); const writer = await overview.createWritable(); await writer.write(gardenOverview()); await writer.close(); toast("已保存到你的表达素材库。", "success"); track("garden_written"); } catch (error) { if (error.name !== "AbortError") toast("无法写入文件夹，已下载为 Markdown 笔记。", "success"); } }
function downloadGarden() { const cards = state.cards.filter((card) => state.selected.includes(card.id)); if (!cards.length) return toast("先选择想保存的知识卡。 "); download("本轮拆解总览.md", gardenOverview(), "text/markdown;charset=utf-8"); cards.forEach((card) => download(`${card.category}-${safeName(card.idea)}.md`, gardenNote(card), "text/markdown;charset=utf-8")); toast("已下载为 Markdown 笔记，可拖入 Obsidian。", "success"); }
function renderFeynman() { const target = document.querySelector("#practice-work"); const options = state.cards.map((card) => `<option value="${card.id}">${esc(card.idea)}</option>`).join(""); target.innerHTML = `<section class="practice-work"><p class="eyebrow">费曼技巧</p><label>选择一张卡，或写下自己的主题<select id="feynman-card"><option value="">我的主题</option>${options}</select></label><textarea id="feynman-text" placeholder="试着把它讲给一个完全不懂的人听……"></textarea><button class="primary" id="feynman-button">请继续问我</button><p class="question" id="feynman-question" hidden></p></section>`; document.querySelector("#feynman-button").addEventListener("click", () => { const text = document.querySelector("#feynman-text").value.trim(); if (!text) return toast("先用自己的话讲一点。"); const prompts = ["如果对方从没见过这个概念，你会先举哪个生活中的例子？", "这里最容易被误解的一个词是什么？", "它在哪种情况下不成立？", "你能不用术语再讲一遍吗？"]; const box = document.querySelector("#feynman-question"); box.textContent = prompts[Math.abs(hash(text)) % prompts.length]; box.hidden = false; }); }
function renderFifteen() { const target = document.querySelector("#practice-work"); target.innerHTML = `<section class="practice-work"><p class="eyebrow">十五分钟，留下一段自己的话</p><div class="timer-row"><b id="timer">15:00</b><span id="practice-count">${state.practiceText.length} / 300 字</span></div><textarea id="practice-text" placeholder="今天真正想明白的一点是……">${esc(state.practiceText)}</textarea><div class="screen-action"><button class="quiet" id="start-timer">开始 15 分钟</button><button class="primary" id="carry-practice">保存这段练习</button></div></section>`; document.querySelector("#practice-text").addEventListener("input", (event) => { state.practiceText = event.target.value; save(); document.querySelector("#practice-count").textContent = `${state.practiceText.length} / 300 字`; }); document.querySelector("#start-timer").addEventListener("click", startTimer); document.querySelector("#carry-practice").addEventListener("click", () => { save(); toast("这段练习已经保存，之后会在正式写作时作为你的材料。", "success"); }); }
function startTimer() { const started = Date.now(); clearInterval(startTimer.id); startTimer.id = setInterval(() => { const left = Math.max(0, 900 - Math.floor((Date.now() - started) / 1000)); const node = document.querySelector("#timer"); if (node) node.textContent = `${String(Math.floor(left / 60)).padStart(2,"0")}:${String(left % 60).padStart(2,"0")}`; if (!left) { clearInterval(startTimer.id); toast("十五分钟到了。这段练习已经留在当前浏览器里。", "success"); } }, 250); }
function downloadHtml() { captureDraft(); const theme = state.theme || "magazine"; const title = esc(state.title.trim() || "未命名文章"); const css = { magazine:"--page:#fff9f7;--ink:#57313f;--accent:#d96175;--soft:#ffe7e5;", newspaper:"--page:#f8fbfd;--ink:#344756;--accent:#6287a0;--soft:#e3edf2;", lavender:"--page:#fffbff;--ink:#59466f;--accent:#9674b0;--soft:#eee6f7;" }[theme] || ""; const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{margin:0;background:var(--page);color:var(--ink);font-family:PingFang SC,Microsoft YaHei,serif}main{max-width:720px;margin:auto;padding:54px 28px 80px}header{margin-bottom:34px;padding-bottom:19px;border-bottom:2px solid var(--accent)}header span{color:var(--accent);font-size:11px;letter-spacing:1.4px}h1{margin:12px 0 0;font-family:Georgia,STSong,serif;font-size:38px;line-height:1.32}.preview-content p{margin:0 0 22px;font-size:17px;letter-spacing:.35px;line-height:2}.preview-lede{font-size:20px!important;font-weight:700;line-height:1.8!important}.preview-pullquote{margin:28px 0;padding:20px;border-left:4px solid var(--accent);background:var(--soft);font-size:22px;line-height:1.65}.newspaper .preview-content{column-count:2;column-gap:34px}.newspaper .preview-content p:first-child{column-span:all}.newspaper .preview-rule{height:1px;margin:18px 0;background:var(--accent)}.lavender header{padding:22px;border-left:5px solid var(--accent);background:var(--soft)}.lavender .preview-content{padding-left:24px;border-left:1px solid var(--accent)}mark{padding:1px 3px;background:var(--soft);color:inherit}@media(max-width:620px){main{padding:36px 22px 58px}h1{font-size:32px}.newspaper .preview-content{column-count:1}}</style></head><body><main class="${theme}" style="${css}">${preview(theme)}</main></body></html>`; download(`我的文章-${formatThemes[theme]?.label || "排版"}.html`, html, "text/html;charset=utf-8"); toast("排版文章已经保存。", "success"); }
function download(name, content, type) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
function toast(message, type = "") { const box = document.querySelector("#toast"); if (!box) return; box.textContent = message; box.className = `toast ${type}`; box.hidden = false; clearTimeout(toast.id); toast.id = setTimeout(() => { box.hidden = true; }, 2800); }

render();
